name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    # Setup inputs
    inputs:
      dinner:
        type: choice
        description: Select dinner
        options:
         - Ramen🍜
         - Curry🍛
         - Bear🍺
      is-large:
        type: boolean
        description: Do you want large size?
      environment:
        type: environment
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Dinner
        run: |
          echo "Dinner\: ${{ github.event.inpouts.dinner }}"
          echo "Is Large?\: ${{ github.event.inpouts.is-large }}"
          echo "Selected Env\: ${{ github.event.inpouts.environment }}"
