name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    # Setup inputs
    inputs:
      dinner:
        type: choice
        description: Select dinner
        options:
         - Ramen🍜
         - Curry🍛
         - Bear🍺
      is-large:
        type: boolean
        description: Do you want large size?
      environment:
        type: environment
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - uses: actions/checkout@v2

      # Display selected values
      - name: Selections
        run: |
          echo "Dinner: ${{ github.event.inputs.dinner }}"
          echo "Is Large?: ${{ github.event.inputs.is-large }}"
          echo "Selected Env: ${{ github.event.inputs.environment }}"
          echo "APP_ENV: ${{ secrets.APP_ENV }}"
